// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EcoBO.Models;

public partial class CommunityInteraction
{
    public Guid Id { get; set; }

    public Guid UserId { get; set; }

    public Guid TargetId { get; set; }

    public string TargetType { get; set; }

    public string InteractionType { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual User User { get; set; }
}