// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EcoBO.Models;

public partial class CommunityPostTag
{
    public Guid PostId { get; set; }

    public Guid HashtagId { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual CommunityHashtag Hashtag { get; set; }

    public virtual CommunityPost Post { get; set; }
}