// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EcoBO.Models;

public partial class CommunityPost
{
    public Guid Id { get; set; }

    public Guid UserId { get; set; }

    public string Title { get; set; }

    public string Slug { get; set; }

    public string Content { get; set; }

    public List<string> MediaUrls { get; set; }

    public string Metadata { get; set; }

    public string ThumbnailUrl { get; set; }

    public int? ViewCount { get; set; }

    public int? CommentCount { get; set; }

    public int? LikeCount { get; set; }

    public string Status { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public DateTime? DeletedAt { get; set; }

    public virtual ICollection<CommunityComment> CommunityComments { get; set; } = new List<CommunityComment>();

    public virtual ICollection<CommunityPostTag> CommunityPostTags { get; set; } = new List<CommunityPostTag>();

    public virtual User User { get; set; }
}