// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EcoBO.Models;

public partial class CommunityHashtag
{
    public Guid Id { get; set; }

    public string TagName { get; set; }

    public int? UsageCount { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual ICollection<CommunityPostTag> CommunityPostTags { get; set; } = new List<CommunityPostTag>();
}