// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EcoBO.Models;

public partial class CommunityComment
{
    public Guid Id { get; set; }

    public Guid PostId { get; set; }

    public Guid UserId { get; set; }

    public Guid? ParentCommentId { get; set; }

    public string Content { get; set; }

    public string MediaUrl { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public DateTime? DeletedAt { get; set; }

    public virtual ICollection<CommunityComment> InverseParentComment { get; set; } = new List<CommunityComment>();

    public virtual CommunityComment ParentComment { get; set; }

    public virtual CommunityPost Post { get; set; }

    public virtual User User { get; set; }
}