// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EcoBO.Models;

public partial class EventRegistration
{
    public Guid Id { get; set; }

    public Guid EventId { get; set; }

    public Guid? UserId { get; set; }

    public string ParticipantName { get; set; }

    public string ParticipantEmail { get; set; }

    public string ParticipantPhone { get; set; }

    public string Status { get; set; }

    public DateTime? RegisteredAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual CommunityEvent Event { get; set; }

    public virtual User User { get; set; }
}