// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EcoBO.Models;

public partial class Transactionhistory
{
    public DateTime? DateTrade { get; set; }

    public double? Amount { get; set; }

    public string Status { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public DateTime? DeletedAt { get; set; }

    public string OrderCode { get; set; }

    public string Description { get; set; }

    public Guid Id { get; set; }
}