// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EcoBO.Models;

public partial class WebLog
{
    public Guid Id { get; set; }

    public string IpAddress { get; set; }

    public string UserAgent { get; set; }

    public string ReferrerUrl { get; set; }

    public string PageUrl { get; set; }

    public string EventType { get; set; }

    public string ErrorCode { get; set; }

    public string ErrorMessage { get; set; }

    public int? TimeOnPage { get; set; }

    public DateTime? CreatedAt { get; set; }
}